services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: DouniaApp
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "DouniaApp"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - "5434:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: ./
      dockerfile: AppDounia.API/Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=DouniaApp;Username=postgres;Password=1234"
      ASPNETCORE_URLS: "http://+:8080"
      ASPNETCORE_ENVIRONMENT: "Production"
      ASPNETCORE_HTTP_PORTS: "8080"
      ASPNETCORE_HTTPS_PORT: ""
    ports:
      - "5000:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    restart: unless-stopped

volumes:
  dbdata: