version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: DouniaApp
    ports:
      - "5434:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data

  api:
    build:
      context: ./       # <-- racine du repo
      dockerfile: AppDounia.API/Dockerfile
    depends_on:
      - db
    environment:
      ConnectionStrings__DefaultConnection: "Host=db;Port=5432;Database=DouniaApp;Username=postgres;Password=1234"
    ports:
      - "5000:80"

volumes:
  dbdata:
